cloud:
  aws:
    credentials:
      access-key: AKIAR6XEY346BBHABKOW
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: demospringboots3userbucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 50MB

server:
  port: 9090